// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB01Tm-VMFKdwOfNTsbnHAMo7DZssA7qwE',
    appId: '1:1038805052496:web:placeholder',
    messagingSenderId: '1038805052496',
    projectId: 'nitadompetdgtl',
    storageBucket: 'nitadompetdgtl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01Tm-VMFKdwOfNTsbnHAMo7DZssA7qwE',
    appId: '1:1038805052496:android:df11ad4284e80e85293555',
    messagingSenderId: '1038805052496',
    projectId: 'nitadompetdgtl',
    storageBucket: 'nitadompetdgtl.firebasestorage.app',
  );
}
